"""Export extracted features to shapefiles and coordinate CSVs."""

from __future__ import annotations

import csv
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from xml.etree.ElementTree import Element, SubElement, ElementTree

import geopandas as gpd
import numpy as np
import pyproj
import rasterio
from rasterio.transform import from_gcps
from pyproj import Transformer
from shapely.geometry import LineString, Point

from pipeline.extract_features import ExtractedFeatures
from pipeline.topology import ManholePipeLink, TopologyResult
from pipeline.tps_transform import PixelGeoTransform, make_transform_fn


def _pixel_to_geo(
    x: float,
    y: float,
    transform_method,
) -> tuple[float, float]:
    """Transform pixel (col, row) to lon/lat using rasterio transform."""
    lon, lat = transform_method(y, x)
    return float(lon), float(lat)


def _build_transform_fn(geotiff_path: str | Path):
    """Return a function mapping (row, col) -> (lon, lat)."""
    with rasterio.open(str(geotiff_path)) as src:
        transform = src.transform
        gcps = src.gcps[0] if src.gcps else None

        # If transform is identity, derive from stored GCPs
        if transform.a == 1.0 and transform.e == 1.0 and transform.b == 0 and transform.d == 0:
            if gcps and len(gcps) >= 3:
                transform = from_gcps(gcps)
            else:
                raise RuntimeError(
                    "GeoTIFF has identity transform and no usable GCPs. Re-run georeferencing."
                )

        frozen_transform = transform

    def fn(row: float, col: float) -> tuple[float, float]:
        lon, lat = rasterio.transform.xy(frozen_transform, row, col)
        return float(lon), float(lat)

    return fn


def _write_qmd(shp_path: Path, title: str, abstract: str, crs: str) -> None:
    """Write minimal QGIS 3 .qmd metadata sidecar."""
    qmd_path = shp_path.with_suffix(".qmd")
    root = Element("qgis")
    root.set("version", "3.34.0")
    root.set("saveUser", "")
    root.set("saveUserFull", "")
    root.set("saveDateTime", datetime.now(timezone.utc).isoformat())

    ident = SubElement(root, "identifier")
    ident.text = shp_path.stem

    title_el = SubElement(root, "title")
    title_el.text = title

    abstract_el = SubElement(root, "abstract")
    abstract_el.text = abstract

    crs_el = SubElement(root, "crs")
    spatial_ref = SubElement(crs_el, "spatialrefsys")
    authid = SubElement(spatial_ref, "authid")
    authid.text = crs

    history = SubElement(root, "history")
    history.text = f"Generated by Bakchodi Ward Map Pipeline at {datetime.now(timezone.utc).isoformat()}"

    tree = ElementTree(root)
    tree.write(qmd_path, encoding="UTF-8", xml_declaration=True)


def export_shapefiles(
    features: ExtractedFeatures,
    topology: TopologyResult,
    output_dir: str | Path,
    config: dict[str, Any],
    pixel_transform: PixelGeoTransform | None = None,
    geotiff_path: str | Path | None = None,
) -> dict[str, Path]:
    """Export drainage, manholes, ward boundary shapefiles and CSVs."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    crs = config["crs"]["output"]
    utm_crs = config["crs"]["utm"]
    transformer = Transformer.from_crs(crs, utm_crs, always_xy=True)

    if pixel_transform is not None:
        to_geo = make_transform_fn(pixel_transform)
    elif geotiff_path is not None:
        to_geo = _build_transform_fn(geotiff_path)
    else:
        raise ValueError("Provide pixel_transform or geotiff_path for coordinate export")

    # --- Drainage network ---
    drainage_rows = []
    for seg in topology.drainage:
        geo_coords = [_pixel_to_geo(x, y, to_geo) for x, y in seg.coords]
        if len(geo_coords) < 2:
            continue
        ls = LineString(geo_coords)
        utm_coords = [transformer.transform(lon, lat) for lon, lat in geo_coords]
        utm_ls = LineString(utm_coords)
        length_m = utm_ls.length
        if not np.isfinite(length_m):
            length_m = 0.0
        drainage_rows.append(
            {
                "seg_id": seg.seg_id,
                "pipe_class": seg.pipe_class,
                "color": seg.color,
                "length_m": round(length_m, 2),
                "geometry": ls,
            }
        )

    drainage_shp = output_dir / "drainage_network.shp"
    drainage_gdf = gpd.GeoDataFrame(drainage_rows, crs=crs) if drainage_rows else gpd.GeoDataFrame(crs=crs)
    if not drainage_gdf.empty:
        drainage_gdf.to_file(drainage_shp, driver="ESRI Shapefile")
        _write_qmd(
            drainage_shp,
            "Ward Drainage Network",
            "Extracted drainage/sewer lines from municipal ward map.",
            crs,
        )
        drainage_gdf.to_file(output_dir / "drainage_network.geojson", driver="GeoJSON")

    # --- Manholes ---
    mh_rows = []
    for mh in topology.manholes:
        lon, lat = _pixel_to_geo(mh.x, mh.y, to_geo)
        easting, northing = transformer.transform(lon, lat)
        mh_rows.append(
            {
                "mh_id": mh.mh_id,
                "type": mh.color,
                "invert_lvl": mh.invert_level if mh.invert_level is not None else -9999,
                "lon": round(lon, 8),
                "lat": round(lat, 8),
                "eastng": round(easting, 2),
                "northng": round(northing, 2),
                "geometry": Point(lon, lat),
            }
        )

    manholes_shp = output_dir / "manholes.shp"
    manholes_gdf = gpd.GeoDataFrame(mh_rows, crs=crs) if mh_rows else gpd.GeoDataFrame(crs=crs)
    if not manholes_gdf.empty:
        manholes_gdf.to_file(manholes_shp, driver="ESRI Shapefile")
        _write_qmd(
            manholes_shp,
            "Ward Manholes / Potholes",
            "Detected manhole and pothole point features with coordinates.",
            crs,
        )
        manholes_gdf.to_file(output_dir / "manholes.geojson", driver="GeoJSON")

    # --- Ward boundary ---
    if features.ward_boundary is not None:
        wb_coords = [
            _pixel_to_geo(x, y, to_geo) for x, y in features.ward_boundary.coords
        ]
        wb_ls = LineString(wb_coords)
        ward_gdf = gpd.GeoDataFrame(
            [
                {
                    "ward_no": config["ward"]["number"],
                    "area_acre": config["ward"]["area_acres"],
                    "geometry": wb_ls,
                }
            ],
            crs=crs,
        )
        ward_shp = output_dir / "ward_boundary.shp"
        ward_gdf.to_file(ward_shp, driver="ESRI Shapefile")
        _write_qmd(
            ward_shp,
            f"Ward {config['ward']['number']} Boundary",
            "Ward boundary extracted from magenta dashed line on source map.",
            crs,
        )
        ward_gdf.to_file(output_dir / "ward_boundary.geojson", driver="GeoJSON")

    # --- CSV exports ---
    _export_coordinates_csv(topology.manholes, to_geo, transformer, output_dir / "coordinates.csv")
    _export_links_csv(topology.links, output_dir / "manhole_pipe_links.csv")

    return {
        "drainage": drainage_shp if not drainage_gdf.empty else None,
        "manholes": manholes_shp if not manholes_gdf.empty else None,
        "ward_boundary": output_dir / "ward_boundary.shp" if features.ward_boundary else None,
    }


def _export_coordinates_csv(
    manholes,
    to_geo,
    transformer,
    path: Path,
) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["mh_id", "type", "invert_level", "lon", "lat", "easting", "northing"],
        )
        writer.writeheader()
        for mh in manholes:
            lon, lat = _pixel_to_geo(mh.x, mh.y, to_geo)
            easting, northing = transformer.transform(lon, lat)
            writer.writerow(
                {
                    "mh_id": mh.mh_id,
                    "type": mh.color,
                    "invert_level": mh.invert_level if mh.invert_level is not None else "",
                    "lon": round(lon, 8),
                    "lat": round(lat, 8),
                    "easting": round(easting, 2),
                    "northing": round(northing, 2),
                }
            )


def _export_links_csv(links: list[ManholePipeLink], path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "manhole_id",
                "pipe_segment_id",
                "pipe_diameter_class",
                "distance_snap_m",
            ],
        )
        writer.writeheader()
        for link in links:
            writer.writerow(
                {
                    "manhole_id": link.manhole_id,
                    "pipe_segment_id": link.pipe_segment_id,
                    "pipe_diameter_class": link.pipe_diameter_class,
                    "distance_snap_m": link.distance_snap_m,
                }
            )
